import turtle
t = turtle.Turtle()
turtle.title('A Day at the Zoo')
t.ht()
turtle.setup(420,420)
#get words
adj1 = turtle.textinput('Adjective','Enter an adjective: ')
noun1 = turtle.textinput('Noun','Enter a noun: ')
verb1 = turtle.textinput('Verb','Enter a past tense verb: ')
adv1 = turtle.textinput('Adverb','Enter an adverb: ')
adj2 = turtle.textinput('Adjective','Enter an adjective: ')
noun2 = turtle.textinput('Noun','Enter a noun: ')
noun3 = turtle.textinput('Noun','Enter a noun: ')
adj3 = turtle.textinput('Adjective','Enter an adjective: ')
verb2 = turtle.textinput('Verb','Enter a verb: ')
adv2 = turtle.textinput('Adverb','Enter an adverb: ')
verb3 = turtle.textinput('Verb','Enter a past tense verb: ')
adj4 = turtle.textinput('Adjective','Enter an adjective: ')

#print story
t.speed(1)
t.ht()
t.pu()
t.seth(270)
t.setpos(-150,100)
t.write('A Day at the Zoo!',font=('Arial',8,'underline'))
t.fd(200)
t.bk(180)
t.write('Today I went to the zoo.')
t.fd(200)
t.bk(180)
t.write('I saw a(n) {} {} jumping up and down in its tree.'.format(adj1,noun1))
t.fd(200)
t.bk(180)
t.write('He {} {} through the large tunnel that led to its {} {}.'.format(verb1,adv1,adj2,noun2))
t.fd(200)
t.bk(180)
t.write('I got some peanuts and passed them through the')
t.fd(20)
t.write('cage to a gigantic gray {} towering above my head.'.format(noun3))
t.fd(200)
t.bk(180)
t.write('Feeding that animal made me hungry.')
t.fd(200)
t.bk(180)
t.write('I went to get a {} scoop of ice cream.'.format(adj3))
t.fd(200)
t.bk(180)
t.write('It filled my stomach.')
t.fd(200)
t.bk(180)
t.write('Afterwards I had to {} {} to catch our bus.'.format(verb2,adv2))
t.fd(200)
t.bk(180)
t.write('When I got home I {} my mom for a {} day at the zoo.'.format(verb3,adj4))
    

turtle.mainloop()